apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: vim
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vim
    app.kubernetes.io/part-of: rpm-build
  name: vim
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: vim
status:
  loadBalancer: {}
